sudo: required
services:
  - docker

before_install:
  - docker build -t beldeanucalin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true beldeanucalin/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket-name: "elasticbeanstalk-us-east-1-024178468212"
  bucket-path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
